working docker setup
reichlab/flusion pull request #25
Opened 2024-04-23 00:07 UTC by elray1

2024-04-30 19:35 UTC, bsweger requested changes
If you decide to merge this, I'd suggest updated the README for the Docker build command that works on macbooks with the M-series chip:

`docker build --platform linux/amd64 -t flusion .`

2024-04-30 21:59 UTC, matthewcornell commented on README.md
maybe goes without saying?:
```bash
cd <this repo's root>
```

2024-04-30 21:59 UTC, matthewcornell commented
@elray1 this looks good to me. I'd say merge it!

2024-05-01 18:41 UTC, elray1 commented
Thanks for the reviews.  I updated the readme to add the command that needs to be used on macs with M-series chips.  Will merge!

2024-05-01 18:41 UTC, merged